### ISSUE TITLE
Differences with `WDI`?

### ISSUE THREAD

**Issue by etiennebacher** [tidy-intelligence/r-wdi2#1]
Hi, I just discovered your package via the RWeekly page. As a regular user of `WDI`, I was a bit surprised by the statement at the top of the README:

> However, ‘wdi2’ differs *[from the ‘WDI’ package]* by relying on ‘httr2’ for multi-page request and error handling, providing support for downloading multiple indicators with a single function call, using progress bars to keep users informed about the data processing, and returning the processed data in a tidy data format.

(I added the text in italics)

`WDI` can also download several indicators at once and the default output is tidy:

``` r
library(WDI)

WDI(country = c("MX", "CA", "US"), indicator = c("NY.GDP.PCAP.KD", "SP.POP.TOTL")) |> 
  head()
#>   country iso2c iso3c year NY.GDP.PCAP.KD SP.POP.TOTL
#> 1  Canada    CA   CAN 1960       15432.47    17909356
#> 2  Canada    CA   CAN 1961       15605.52    18271000
#> 3  Canada    CA   CAN 1962       16455.75    18614000
#> 4  Canada    CA   CAN 1963       17007.69    18964000
#> 5  Canada    CA   CAN 1964       17800.86    19325000
#> 6  Canada    CA   CAN 1965       18585.88    19678000
```

Therefore I'm not sure I understand how this package is positioned compared to `WDI`? I have nothing against you or your package, but I think the R packages ecosystem is already quite fragmented and that it makes it harder to recommend specific packages to average users, so I think it would be helpful to clarify the differences between the two packages. 

I hope this (unsolicited) feedback is helpful, thank you

**Comment by christophscheuch** [comment]
Hi @etiennebacher! 

Thanks for reaching out and your feedback. I apologize for missing the feature to download multiple indicators using WDI, I can't explain how this happened. I'll correct the README asap. 

I started out with wdi2 package because I'm working on a piece about using Generative AI for R package development, where I wanted to have a simple API (World Bank) but use a new technology (httr2). I'll try to clarify the benefits and positioning and reach out to you for feedback again once I'm done. 

Best,
Christoph

**Comment by m-muecke** [comment]
Might be of interest. I've also published a R package for the world bank indicators using httr2: https://github.com/m-muecke/worldbank

**Comment by christophscheuch** [comment]
@etiennebacher maybe a better way forward is to make my package sound less like a replacement or in direct competition with `WDI`. I could rename my package to e.g.`wbwdi`, remove the direct reference to `WDI`  and ask CRAN to archive the current release of `wdi2`. 

Sorry again for the inconvenience, I should have been more patient and thorough before releasing the package.

**Comment by etiennebacher** [comment]
> maybe a better way forward is to make my package sound less like a replacement or in direct competition with WDI. I could rename my package to e.g.wbwdi, remove the direct reference to WDI and ask CRAN to archive the current release of wdi2.

I guess so, but I think overall I just don't really understand the usecase of this package. It might be because my personal usecase of `WDI` is very simple: I just download a few indicators for a given list of countries and time period, I save them and then reuse the files. So I've never had the need for progress bars or error handling because the download time is quite short and errors only occur when I don't have internet or the indicator doesn't exist anymore (and I find error messages of `WDI` clear enough). That said, maybe you have usecases where relying on `httr2` in the background is useful, I don't know. 

I also see how it can be a nice demo of how one can use generative AI to build a package, I just don't understand why you go through the effort of putting it on CRAN. But all in all, it's not really important and I'm just one person giving feedback, don't give too much weight to that ;)

**Comment by christophscheuch** [comment]
I’ve submitted a request to archive my wdi2 package to the CRAN maintainers. After receiving confirmation, I plan to rename the package and this repo. I might consider resubmitting it to CRAN once it is successfully integrated into the larger project that I’m currently developing (apart from the gen AI demo).

**Comment by christophscheuch** [comment]
'wdi2' is archived, repo will be renamed now. Issue closed.
